import {
    AccountBookFilled,
    AccountBookOutlined,
    AccountBookTwoTone,
    AimOutlined,
    AlertFilled,
    AlertOutlined,
    AlertTwoTone,
    AlibabaOutlined,
    AlignCenterOutlined,
    AlignLeftOutlined,
    AlignRightOutlined,
    AlipayCircleFilled,
    AlipayCircleOutlined,
    AlipayOutlined,
    AlipaySquareFilled,
    AliwangwangFilled,
    AliwangwangOutlined,
    AliyunOutlined,
    AmazonCircleFilled,
    AmazonOutlined,
    AmazonSquareFilled,
    AndroidFilled,
    AndroidOutlined,
    AntCloudOutlined,
    AntDesignOutlined,
    ApartmentOutlined,
    ApiFilled,
    ApiOutlined,
    ApiTwoTone,
    AppleFilled,
    AppleOutlined,
    AppstoreAddOutlined,
    AppstoreFilled,
    AppstoreOutlined,
    AppstoreTwoTone,
    AreaChartOutlined,
    ArrowDownOutlined,
    ArrowLeftOutlined,
    ArrowRightOutlined,
    ArrowUpOutlined,
    ArrowsAltOutlined,
    AudioFilled,
    AudioMutedOutlined,
    AudioOutlined,
    AudioTwoTone,
    AuditOutlined,
    BackwardFilled,
    BackwardOutlined,
    BankFilled,
    BankOutlined,
    BankTwoTone,
    BarChartOutlined,
    BarcodeOutlined,
    BarsOutlined,
    BehanceCircleFilled,
    BehanceOutlined,
    BehanceSquareFilled,
    BehanceSquareOutlined,
    BellFilled,
    BellOutlined,
    BellTwoTone,
    BgColorsOutlined,
    BlockOutlined,
    BoldOutlined,
    BookFilled,
    BookOutlined,
    BookTwoTone,
    BorderBottomOutlined,
    BorderHorizontalOutlined,
    BorderInnerOutlined,
    BorderLeftOutlined,
    BorderOuterOutlined,
    BorderOutlined,
    BorderRightOutlined,
    BorderTopOutlined,
    BorderVerticleOutlined,
    BorderlessTableOutlined,
    BoxPlotFilled,
    BoxPlotOutlined,
    BoxPlotTwoTone,
    BranchesOutlined,
    BugFilled,
    BugOutlined,
    BugTwoTone,
    BuildFilled,
    BuildOutlined,
    BuildTwoTone,
    BulbFilled,
    BulbOutlined,
    BulbTwoTone,
    CalculatorFilled,
    CalculatorOutlined,
    CalculatorTwoTone,
    CalendarFilled,
    CalendarOutlined,
    CalendarTwoTone,
    CameraFilled,
    CameraOutlined,
    CameraTwoTone,
    CarFilled,
    CarOutlined,
    CarTwoTone,
    CaretDownFilled,
    CaretDownOutlined,
    CaretLeftFilled,
    CaretLeftOutlined,
    CaretRightFilled,
    CaretRightOutlined,
    CaretUpFilled,
    CaretUpOutlined,
    CarryOutFilled,
    CarryOutOutlined,
    CarryOutTwoTone,
    CheckCircleFilled,
    CheckCircleOutlined,
    CheckCircleTwoTone,
    CheckOutlined,
    CheckSquareFilled,
    CheckSquareOutlined,
    CheckSquareTwoTone,
    ChromeFilled,
    ChromeOutlined,
    CiCircleFilled,
    CiCircleOutlined,
    CiCircleTwoTone,
    CiOutlined,
    CiTwoTone,
    ClearOutlined,
    ClockCircleFilled,
    ClockCircleOutlined,
    ClockCircleTwoTone,
    CloseCircleFilled,
    CloseCircleOutlined,
    CloseCircleTwoTone,
    CloseOutlined,
    CloseSquareFilled,
    CloseSquareOutlined,
    CloseSquareTwoTone,
    CloudDownloadOutlined,
    CloudFilled,
    CloudOutlined,
    CloudServerOutlined,
    CloudSyncOutlined,
    CloudTwoTone,
    CloudUploadOutlined,
    ClusterOutlined,
    CodeFilled,
    CodeOutlined,
    CodeSandboxCircleFilled,
    CodeSandboxOutlined,
    CodeSandboxSquareFilled,
    CodeTwoTone,
    CodepenCircleFilled,
    CodepenCircleOutlined,
    CodepenOutlined,
    CodepenSquareFilled,
    CoffeeOutlined,
    ColumnHeightOutlined,
    ColumnWidthOutlined,
    CommentOutlined,
    CompassFilled,
    CompassOutlined,
    CompassTwoTone,
    CompressOutlined,
    ConsoleSqlOutlined,
    ContactsFilled,
    ContactsOutlined,
    ContactsTwoTone,
    ContainerFilled,
    ContainerOutlined,
    ContainerTwoTone,
    ControlFilled,
    ControlOutlined,
    ControlTwoTone,
    CopyFilled,
    CopyOutlined,
    CopyTwoTone,
    CopyrightCircleFilled,
    CopyrightCircleOutlined,
    CopyrightCircleTwoTone,
    CopyrightOutlined,
    CopyrightTwoTone,
    CreditCardFilled,
    CreditCardOutlined,
    CreditCardTwoTone,
    CrownFilled,
    CrownOutlined,
    CrownTwoTone,
    CustomerServiceFilled,
    CustomerServiceOutlined,
    CustomerServiceTwoTone,
    DashOutlined,
    DashboardFilled,
    DashboardOutlined,
    DashboardTwoTone,
    DatabaseFilled,
    DatabaseOutlined,
    DatabaseTwoTone,
    DeleteColumnOutlined,
    DeleteFilled,
    DeleteOutlined,
    DeleteRowOutlined,
    DeleteTwoTone,
    DeliveredProcedureOutlined,
    DeploymentUnitOutlined,
    DesktopOutlined,
    DiffFilled,
    DiffOutlined,
    DiffTwoTone,
    DingdingOutlined,
    DingtalkCircleFilled,
    DingtalkOutlined,
    DingtalkSquareFilled,
    DisconnectOutlined,
    DislikeFilled,
    DislikeOutlined,
    DislikeTwoTone,
    DollarCircleFilled,
    DollarCircleOutlined,
    DollarCircleTwoTone,
    DollarOutlined,
    DollarTwoTone,
    DotChartOutlined,
    DoubleLeftOutlined,
    DoubleRightOutlined,
    DownCircleFilled,
    DownCircleOutlined,
    DownCircleTwoTone,
    DownOutlined,
    DownSquareFilled,
    DownSquareOutlined,
    DownSquareTwoTone,
    DownloadOutlined,
    DragOutlined,
    DribbbleCircleFilled,
    DribbbleOutlined,
    DribbbleSquareFilled,
    DribbbleSquareOutlined,
    DropboxCircleFilled,
    DropboxOutlined,
    DropboxSquareFilled,
    EditFilled,
    EditOutlined,
    EditTwoTone,
    EllipsisOutlined,
    EnterOutlined,
    EnvironmentFilled,
    EnvironmentOutlined,
    EnvironmentTwoTone,
    EuroCircleFilled,
    EuroCircleOutlined,
    EuroCircleTwoTone,
    EuroOutlined,
    EuroTwoTone,
    ExceptionOutlined,
    ExclamationCircleFilled,
    ExclamationCircleOutlined,
    ExclamationCircleTwoTone,
    ExclamationOutlined,
    ExpandAltOutlined,
    ExpandOutlined,
    ExperimentFilled,
    ExperimentOutlined,
    ExperimentTwoTone,
    ExportOutlined,
    EyeFilled,
    EyeInvisibleFilled,
    EyeInvisibleOutlined,
    EyeInvisibleTwoTone,
    EyeOutlined,
    EyeTwoTone,
    FacebookFilled,
    FacebookOutlined,
    FallOutlined,
    FastBackwardFilled,
    FastBackwardOutlined,
    FastForwardFilled,
    FastForwardOutlined,
    FieldBinaryOutlined,
    FieldNumberOutlined,
    FieldStringOutlined,
    FieldTimeOutlined,
    FileAddFilled,
    FileAddOutlined,
    FileAddTwoTone,
    FileDoneOutlined,
    FileExcelFilled,
    FileExcelOutlined,
    FileExcelTwoTone,
    FileExclamationFilled,
    FileExclamationOutlined,
    FileExclamationTwoTone,
    FileFilled,
    FileGifOutlined,
    FileImageFilled,
    FileImageOutlined,
    FileImageTwoTone,
    FileJpgOutlined,
    FileMarkdownFilled,
    FileMarkdownOutlined,
    FileMarkdownTwoTone,
    FileOutlined,
    FilePdfFilled,
    FilePdfOutlined,
    FilePdfTwoTone,
    FilePptFilled,
    FilePptOutlined,
    FilePptTwoTone,
    FileProtectOutlined,
    FileSearchOutlined,
    FileSyncOutlined,
    FileTextFilled,
    FileTextOutlined,
    FileTextTwoTone,
    FileTwoTone,
    FileUnknownFilled,
    FileUnknownOutlined,
    FileUnknownTwoTone,
    FileWordFilled,
    FileWordOutlined,
    FileWordTwoTone,
    FileZipFilled,
    FileZipOutlined,
    FileZipTwoTone,
    FilterFilled,
    FilterOutlined,
    FilterTwoTone,
    FireFilled,
    FireOutlined,
    FireTwoTone,
    FlagFilled,
    FlagOutlined,
    FlagTwoTone,
    FolderAddFilled,
    FolderAddOutlined,
    FolderAddTwoTone,
    FolderFilled,
    FolderOpenFilled,
    FolderOpenOutlined,
    FolderOpenTwoTone,
    FolderOutlined,
    FolderTwoTone,
    FolderViewOutlined,
    FontColorsOutlined,
    FontSizeOutlined,
    ForkOutlined,
    FormOutlined,
    FormatPainterFilled,
    FormatPainterOutlined,
    ForwardFilled,
    ForwardOutlined,
    FrownFilled,
    FrownOutlined,
    FrownTwoTone,
    FullscreenExitOutlined,
    FullscreenOutlined,
    FunctionOutlined,
    FundFilled,
    FundOutlined,
    FundProjectionScreenOutlined,
    FundTwoTone,
    FundViewOutlined,
    FunnelPlotFilled,
    FunnelPlotOutlined,
    FunnelPlotTwoTone,
    GatewayOutlined,
    GifOutlined,
    GiftFilled,
    GiftOutlined,
    GiftTwoTone,
    GithubFilled,
    GithubOutlined,
    GitlabFilled,
    GitlabOutlined,
    GlobalOutlined,
    GoldFilled,
    GoldOutlined,
    GoldTwoTone,
    GoldenFilled,
    GoogleCircleFilled,
    GoogleOutlined,
    GooglePlusCircleFilled,
    GooglePlusOutlined,
    GooglePlusSquareFilled,
    GoogleSquareFilled,
    GroupOutlined,
    HddFilled,
    HddOutlined,
    HddTwoTone,
    HeartFilled,
    HeartOutlined,
    HeartTwoTone,
    HeatMapOutlined,
    HighlightFilled,
    HighlightOutlined,
    HighlightTwoTone,
    HistoryOutlined,
    HolderOutlined,
    HomeFilled,
    HomeOutlined,
    HomeTwoTone,
    HourglassFilled,
    HourglassOutlined,
    HourglassTwoTone,
    Html5Filled,
    Html5Outlined,
    Html5TwoTone,
    IdcardFilled,
    IdcardOutlined,
    IdcardTwoTone,
    IeCircleFilled,
    IeOutlined,
    IeSquareFilled,
    ImportOutlined,
    InboxOutlined,
    InfoCircleFilled,
    InfoCircleOutlined,
    InfoCircleTwoTone,
    InfoOutlined,
    InsertRowAboveOutlined,
    InsertRowBelowOutlined,
    InsertRowLeftOutlined,
    InsertRowRightOutlined,
    InstagramFilled,
    InstagramOutlined,
    InsuranceFilled,
    InsuranceOutlined,
    InsuranceTwoTone,
    InteractionFilled,
    InteractionOutlined,
    InteractionTwoTone,
    IssuesCloseOutlined,
    ItalicOutlined,
    KeyOutlined,
    LaptopOutlined,
    LayoutFilled,
    LayoutOutlined,
    LayoutTwoTone,
    LeftCircleFilled,
    LeftCircleOutlined,
    LeftCircleTwoTone,
    LeftOutlined,
    LeftSquareFilled,
    LeftSquareOutlined,
    LeftSquareTwoTone,
    LikeFilled,
    LikeOutlined,
    LikeTwoTone,
    LineChartOutlined,
    LineHeightOutlined,
    LineOutlined,
    LinkOutlined,
    LinkedinFilled,
    LinkedinOutlined,
    Loading3QuartersOutlined,
    LoadingOutlined,
    LockFilled,
    LockOutlined,
    LockTwoTone,
    LoginOutlined,
    LogoutOutlined,
    MacCommandFilled,
    MacCommandOutlined,
    MailFilled,
    MailOutlined,
    MailTwoTone,
    ManOutlined,
    MedicineBoxFilled,
    MedicineBoxOutlined,
    MedicineBoxTwoTone,
    MediumCircleFilled,
    MediumOutlined,
    MediumSquareFilled,
    MediumWorkmarkOutlined,
    MehFilled,
    MehOutlined,
    MehTwoTone,
    MenuFoldOutlined,
    MenuOutlined,
    MenuUnfoldOutlined,
    MergeCellsOutlined,
    MessageFilled,
    MessageOutlined,
    MessageTwoTone,
    MinusCircleFilled,
    MinusCircleOutlined,
    MinusCircleTwoTone,
    MinusOutlined,
    MinusSquareFilled,
    MinusSquareOutlined,
    MinusSquareTwoTone,
    MobileFilled,
    MobileOutlined,
    MobileTwoTone,
    MoneyCollectFilled,
    MoneyCollectOutlined,
    MoneyCollectTwoTone,
    MonitorOutlined,
    MoreOutlined,
    NodeCollapseOutlined,
    NodeExpandOutlined,
    NodeIndexOutlined,
    NotificationFilled,
    NotificationOutlined,
    NotificationTwoTone,
    NumberOutlined,
    OneToOneOutlined,
    OrderedListOutlined,
    PaperClipOutlined,
    PartitionOutlined,
    PauseCircleFilled,
    PauseCircleOutlined,
    PauseCircleTwoTone,
    PauseOutlined,
    PayCircleFilled,
    PayCircleOutlined,
    PercentageOutlined,
    PhoneFilled,
    PhoneOutlined,
    PhoneTwoTone,
    PicCenterOutlined,
    PicLeftOutlined,
    PicRightOutlined,
    PictureFilled,
    PictureOutlined,
    PictureTwoTone,
    PieChartFilled,
    PieChartOutlined,
    PieChartTwoTone,
    PlayCircleFilled,
    PlayCircleOutlined,
    PlayCircleTwoTone,
    PlaySquareFilled,
    PlaySquareOutlined,
    PlaySquareTwoTone,
    PlusCircleFilled,
    PlusCircleOutlined,
    PlusCircleTwoTone,
    PlusOutlined,
    PlusSquareFilled,
    PlusSquareOutlined,
    PlusSquareTwoTone,
    PoundCircleFilled,
    PoundCircleOutlined,
    PoundCircleTwoTone,
    PoundOutlined,
    PoweroffOutlined,
    PrinterFilled,
    PrinterOutlined,
    PrinterTwoTone,
    ProfileFilled,
    ProfileOutlined,
    ProfileTwoTone,
    ProjectFilled,
    ProjectOutlined,
    ProjectTwoTone,
    PropertySafetyFilled,
    PropertySafetyOutlined,
    PropertySafetyTwoTone,
    PullRequestOutlined,
    PushpinFilled,
    PushpinOutlined,
    PushpinTwoTone,
    QqCircleFilled,
    QqOutlined,
    QqSquareFilled,
    QrcodeOutlined,
    QuestionCircleFilled,
    QuestionCircleOutlined,
    QuestionCircleTwoTone,
    QuestionOutlined,
    RadarChartOutlined,
    RadiusBottomleftOutlined,
    RadiusBottomrightOutlined,
    RadiusSettingOutlined,
    RadiusUpleftOutlined,
    RadiusUprightOutlined,
    ReadFilled,
    ReadOutlined,
    ReconciliationFilled,
    ReconciliationOutlined,
    ReconciliationTwoTone,
    RedEnvelopeFilled,
    RedEnvelopeOutlined,
    RedEnvelopeTwoTone,
    RedditCircleFilled,
    RedditOutlined,
    RedditSquareFilled,
    RedoOutlined,
    ReloadOutlined,
    RestFilled,
    RestOutlined,
    RestTwoTone,
    RetweetOutlined,
    RightCircleFilled,
    RightCircleOutlined,
    RightCircleTwoTone,
    RightOutlined,
    RightSquareFilled,
    RightSquareOutlined,
    RightSquareTwoTone,
    RiseOutlined,
    RobotFilled,
    RobotOutlined,
    RocketFilled,
    RocketOutlined,
    RocketTwoTone,
    RollbackOutlined,
    RotateLeftOutlined,
    RotateRightOutlined,
    SafetyCertificateFilled,
    SafetyCertificateOutlined,
    SafetyCertificateTwoTone,
    SafetyOutlined,
    SaveFilled,
    SaveOutlined,
    SaveTwoTone,
    ScanOutlined,
    ScheduleFilled,
    ScheduleOutlined,
    ScheduleTwoTone,
    ScissorOutlined,
    SearchOutlined,
    SecurityScanFilled,
    SecurityScanOutlined,
    SecurityScanTwoTone,
    SelectOutlined,
    SendOutlined,
    SettingFilled,
    SettingOutlined,
    SettingTwoTone,
    ShakeOutlined,
    ShareAltOutlined,
    ShopFilled,
    ShopOutlined,
    ShopTwoTone,
    ShoppingCartOutlined,
    ShoppingFilled,
    ShoppingOutlined,
    ShoppingTwoTone,
    ShrinkOutlined,
    SignalFilled,
    SisternodeOutlined,
    SketchCircleFilled,
    SketchOutlined,
    SketchSquareFilled,
    SkinFilled,
    SkinOutlined,
    SkinTwoTone,
    SkypeFilled,
    SkypeOutlined,
    SlackCircleFilled,
    SlackOutlined,
    SlackSquareFilled,
    SlackSquareOutlined,
    SlidersFilled,
    SlidersOutlined,
    SlidersTwoTone,
    SmallDashOutlined,
    SmileFilled,
    SmileOutlined,
    SmileTwoTone,
    SnippetsFilled,
    SnippetsOutlined,
    SnippetsTwoTone,
    SolutionOutlined,
    SortAscendingOutlined,
    SortDescendingOutlined,
    SoundFilled,
    SoundOutlined,
    SoundTwoTone,
    SplitCellsOutlined,
    StarFilled,
    StarOutlined,
    StarTwoTone,
    StepBackwardFilled,
    StepBackwardOutlined,
    StepForwardFilled,
    StepForwardOutlined,
    StockOutlined,
    StopFilled,
    StopOutlined,
    StopTwoTone,
    StrikethroughOutlined,
    SubnodeOutlined,
    SwapLeftOutlined,
    SwapOutlined,
    SwapRightOutlined,
    SwitcherFilled,
    SwitcherOutlined,
    SwitcherTwoTone,
    SyncOutlined,
    TableOutlined,
    TabletFilled,
    TabletOutlined,
    TabletTwoTone,
    TagFilled,
    TagOutlined,
    TagTwoTone,
    TagsFilled,
    TagsOutlined,
    TagsTwoTone,
    TaobaoCircleFilled,
    TaobaoCircleOutlined,
    TaobaoOutlined,
    TaobaoSquareFilled,
    TeamOutlined,
    ThunderboltFilled,
    ThunderboltOutlined,
    ThunderboltTwoTone,
    ToTopOutlined,
    ToolFilled,
    ToolOutlined,
    ToolTwoTone,
    TrademarkCircleFilled,
    TrademarkCircleOutlined,
    TrademarkCircleTwoTone,
    TrademarkOutlined,
    TransactionOutlined,
    TranslationOutlined,
    TrophyFilled,
    TrophyOutlined,
    TrophyTwoTone,
    TwitterCircleFilled,
    TwitterOutlined,
    TwitterSquareFilled,
    UnderlineOutlined,
    UndoOutlined,
    UngroupOutlined,
    UnlockFilled,
    UnlockOutlined,
    UnlockTwoTone,
    UnorderedListOutlined,
    UpCircleFilled,
    UpCircleOutlined,
    UpCircleTwoTone,
    UpOutlined,
    UpSquareFilled,
    UpSquareOutlined,
    UpSquareTwoTone,
    UploadOutlined,
    UsbFilled,
    UsbOutlined,
    UsbTwoTone,
    UserAddOutlined,
    UserDeleteOutlined,
    UserOutlined,
    UserSwitchOutlined,
    UsergroupAddOutlined,
    UsergroupDeleteOutlined,
    VerifiedOutlined,
    VerticalAlignBottomOutlined,
    VerticalAlignMiddleOutlined,
    VerticalAlignTopOutlined,
    VerticalLeftOutlined,
    VerticalRightOutlined,
    VideoCameraAddOutlined,
    VideoCameraFilled,
    VideoCameraOutlined,
    VideoCameraTwoTone,
    WalletFilled,
    WalletOutlined,
    WalletTwoTone,
    WarningFilled,
    WarningOutlined,
    WarningTwoTone,
    WechatFilled,
    WechatOutlined,
    WeiboCircleFilled,
    WeiboCircleOutlined,
    WeiboOutlined,
    WeiboSquareFilled,
    WeiboSquareOutlined,
    WhatsAppOutlined,
    WifiOutlined,
    WindowsFilled,
    WindowsOutlined,
    WomanOutlined,
    YahooFilled,
    YahooOutlined,
    YoutubeFilled,
    YoutubeOutlined,
    YuqueFilled,
    YuqueOutlined,
    ZhihuCircleFilled,
    ZhihuOutlined,
    ZhihuSquareFilled,
    ZoomInOutlined,
    ZoomOutOutlined,
} from "@ant-design/icons";

export const iconList = [
	{ value: "AccountBookFilled", label: <AccountBookFilled /> },
	{ value: "AccountBookOutlined", label: <AccountBookOutlined /> },
	{ value: "AccountBookTwoTone", label: <AccountBookTwoTone /> },
	{ value: "AimOutlined", label: <AimOutlined /> },
	{ value: "AlertFilled", label: <AlertFilled /> },
	{ value: "AlertOutlined", label: <AlertOutlined /> },
	{ value: "AlertTwoTone", label: <AlertTwoTone /> },
	{ value: "AlibabaOutlined", label: <AlibabaOutlined /> },
	{ value: "AlignCenterOutlined", label: <AlignCenterOutlined /> },
	{ value: "AlignLeftOutlined", label: <AlignLeftOutlined /> },
	{ value: "AlignRightOutlined", label: <AlignRightOutlined /> },
	{ value: "AlipayCircleFilled", label: <AlipayCircleFilled /> },
	{ value: "AlipayCircleOutlined", label: <AlipayCircleOutlined /> },
	{ value: "AlipayOutlined", label: <AlipayOutlined /> },
	{ value: "AlipaySquareFilled", label: <AlipaySquareFilled /> },
	{ value: "AliwangwangFilled", label: <AliwangwangFilled /> },
	{ value: "AliwangwangOutlined", label: <AliwangwangOutlined /> },
	{ value: "AliyunOutlined", label: <AliyunOutlined /> },
	{ value: "AmazonCircleFilled", label: <AmazonCircleFilled /> },
	{ value: "AmazonOutlined", label: <AmazonOutlined /> },
	{ value: "AmazonSquareFilled", label: <AmazonSquareFilled /> },
	{ value: "AndroidFilled", label: <AndroidFilled /> },
	{ value: "AndroidOutlined", label: <AndroidOutlined /> },
	{ value: "AntCloudOutlined", label: <AntCloudOutlined /> },
	{ value: "AntDesignOutlined", label: <AntDesignOutlined /> },
	{ value: "ApartmentOutlined", label: <ApartmentOutlined /> },
	{ value: "ApiFilled", label: <ApiFilled /> },
	{ value: "ApiOutlined", label: <ApiOutlined /> },
	{ value: "ApiTwoTone", label: <ApiTwoTone /> },
	{ value: "AppleFilled", label: <AppleFilled /> },
	{ value: "AppleOutlined", label: <AppleOutlined /> },
	{ value: "AppstoreAddOutlined", label: <AppstoreAddOutlined /> },
	{ value: "AppstoreFilled", label: <AppstoreFilled /> },
	{ value: "AppstoreOutlined", label: <AppstoreOutlined /> },
	{ value: "AppstoreTwoTone", label: <AppstoreTwoTone /> },
	{ value: "AreaChartOutlined", label: <AreaChartOutlined /> },
	{ value: "ArrowDownOutlined", label: <ArrowDownOutlined /> },
	{ value: "ArrowLeftOutlined", label: <ArrowLeftOutlined /> },
	{ value: "ArrowRightOutlined", label: <ArrowRightOutlined /> },
	{ value: "ArrowUpOutlined", label: <ArrowUpOutlined /> },
	{ value: "ArrowsAltOutlined", label: <ArrowsAltOutlined /> },
	{ value: "AudioFilled", label: <AudioFilled /> },
	{ value: "AudioMutedOutlined", label: <AudioMutedOutlined /> },
	{ value: "AudioOutlined", label: <AudioOutlined /> },
	{ value: "AudioTwoTone", label: <AudioTwoTone /> },
	{ value: "AuditOutlined", label: <AuditOutlined /> },
	{ value: "BackwardFilled", label: <BackwardFilled /> },
	{ value: "BackwardOutlined", label: <BackwardOutlined /> },
	{ value: "BankFilled", label: <BankFilled /> },
	{ value: "BankOutlined", label: <BankOutlined /> },
	{ value: "BankTwoTone", label: <BankTwoTone /> },
	{ value: "BarChartOutlined", label: <BarChartOutlined /> },
	{ value: "BarcodeOutlined", label: <BarcodeOutlined /> },
	{ value: "BarsOutlined", label: <BarsOutlined /> },
	{ value: "BehanceCircleFilled", label: <BehanceCircleFilled /> },
	{ value: "BehanceOutlined", label: <BehanceOutlined /> },
	{ value: "BehanceSquareFilled", label: <BehanceSquareFilled /> },
	{ value: "BehanceSquareOutlined", label: <BehanceSquareOutlined /> },
	{ value: "BellFilled", label: <BellFilled /> },
	{ value: "BellOutlined", label: <BellOutlined /> },
	{ value: "BellTwoTone", label: <BellTwoTone /> },
	{ value: "BgColorsOutlined", label: <BgColorsOutlined /> },
	{ value: "BlockOutlined", label: <BlockOutlined /> },
	{ value: "BoldOutlined", label: <BoldOutlined /> },
	{ value: "BookFilled", label: <BookFilled /> },
	{ value: "BookOutlined", label: <BookOutlined /> },
	{ value: "BookTwoTone", label: <BookTwoTone /> },
	{ value: "BorderBottomOutlined", label: <BorderBottomOutlined /> },
	{ value: "BorderHorizontalOutlined", label: <BorderHorizontalOutlined /> },
	{ value: "BorderInnerOutlined", label: <BorderInnerOutlined /> },
	{ value: "BorderLeftOutlined", label: <BorderLeftOutlined /> },
	{ value: "BorderOuterOutlined", label: <BorderOuterOutlined /> },
	{ value: "BorderOutlined", label: <BorderOutlined /> },
	{ value: "BorderRightOutlined", label: <BorderRightOutlined /> },
	{ value: "BorderTopOutlined", label: <BorderTopOutlined /> },
	{ value: "BorderVerticleOutlined", label: <BorderVerticleOutlined /> },
	{ value: "BorderlessTableOutlined", label: <BorderlessTableOutlined /> },
	{ value: "BoxPlotFilled", label: <BoxPlotFilled /> },
	{ value: "BoxPlotOutlined", label: <BoxPlotOutlined /> },
	{ value: "BoxPlotTwoTone", label: <BoxPlotTwoTone /> },
	{ value: "BranchesOutlined", label: <BranchesOutlined /> },
	{ value: "BugFilled", label: <BugFilled /> },
	{ value: "BugOutlined", label: <BugOutlined /> },
	{ value: "BugTwoTone", label: <BugTwoTone /> },
	{ value: "BuildFilled", label: <BuildFilled /> },
	{ value: "BuildOutlined", label: <BuildOutlined /> },
	{ value: "BuildTwoTone", label: <BuildTwoTone /> },
	{ value: "BulbFilled", label: <BulbFilled /> },
	{ value: "BulbOutlined", label: <BulbOutlined /> },
	{ value: "BulbTwoTone", label: <BulbTwoTone /> },
	{ value: "CalculatorFilled", label: <CalculatorFilled /> },
	{ value: "CalculatorOutlined", label: <CalculatorOutlined /> },
	{ value: "CalculatorTwoTone", label: <CalculatorTwoTone /> },
	{ value: "CalendarFilled", label: <CalendarFilled /> },
	{ value: "CalendarOutlined", label: <CalendarOutlined /> },
	{ value: "CalendarTwoTone", label: <CalendarTwoTone /> },
	{ value: "CameraFilled", label: <CameraFilled /> },
	{ value: "CameraOutlined", label: <CameraOutlined /> },
	{ value: "CameraTwoTone", label: <CameraTwoTone /> },
	{ value: "CarFilled", label: <CarFilled /> },
	{ value: "CarOutlined", label: <CarOutlined /> },
	{ value: "CarTwoTone", label: <CarTwoTone /> },
	{ value: "CaretDownFilled", label: <CaretDownFilled /> },
	{ value: "CaretDownOutlined", label: <CaretDownOutlined /> },
	{ value: "CaretLeftFilled", label: <CaretLeftFilled /> },
	{ value: "CaretLeftOutlined", label: <CaretLeftOutlined /> },
	{ value: "CaretRightFilled", label: <CaretRightFilled /> },
	{ value: "CaretRightOutlined", label: <CaretRightOutlined /> },
	{ value: "CaretUpFilled", label: <CaretUpFilled /> },
	{ value: "CaretUpOutlined", label: <CaretUpOutlined /> },
	{ value: "CarryOutFilled", label: <CarryOutFilled /> },
	{ value: "CarryOutOutlined", label: <CarryOutOutlined /> },
	{ value: "CarryOutTwoTone", label: <CarryOutTwoTone /> },
	{ value: "CheckCircleFilled", label: <CheckCircleFilled /> },
	{ value: "CheckCircleOutlined", label: <CheckCircleOutlined /> },
	{ value: "CheckCircleTwoTone", label: <CheckCircleTwoTone /> },
	{ value: "CheckOutlined", label: <CheckOutlined /> },
	{ value: "CheckSquareFilled", label: <CheckSquareFilled /> },
	{ value: "CheckSquareOutlined", label: <CheckSquareOutlined /> },
	{ value: "CheckSquareTwoTone", label: <CheckSquareTwoTone /> },
	{ value: "ChromeFilled", label: <ChromeFilled /> },
	{ value: "ChromeOutlined", label: <ChromeOutlined /> },
	{ value: "CiCircleFilled", label: <CiCircleFilled /> },
	{ value: "CiCircleOutlined", label: <CiCircleOutlined /> },
	{ value: "CiCircleTwoTone", label: <CiCircleTwoTone /> },
	{ value: "CiOutlined", label: <CiOutlined /> },
	{ value: "CiTwoTone", label: <CiTwoTone /> },
	{ value: "ClearOutlined", label: <ClearOutlined /> },
	{ value: "ClockCircleFilled", label: <ClockCircleFilled /> },
	{ value: "ClockCircleOutlined", label: <ClockCircleOutlined /> },
	{ value: "ClockCircleTwoTone", label: <ClockCircleTwoTone /> },
	{ value: "CloseCircleFilled", label: <CloseCircleFilled /> },
	{ value: "CloseCircleOutlined", label: <CloseCircleOutlined /> },
	{ value: "CloseCircleTwoTone", label: <CloseCircleTwoTone /> },
	{ value: "CloseOutlined", label: <CloseOutlined /> },
	{ value: "CloseSquareFilled", label: <CloseSquareFilled /> },
	{ value: "CloseSquareOutlined", label: <CloseSquareOutlined /> },
	{ value: "CloseSquareTwoTone", label: <CloseSquareTwoTone /> },
	{ value: "CloudDownloadOutlined", label: <CloudDownloadOutlined /> },
	{ value: "CloudFilled", label: <CloudFilled /> },
	{ value: "CloudOutlined", label: <CloudOutlined /> },
	{ value: "CloudServerOutlined", label: <CloudServerOutlined /> },
	{ value: "CloudSyncOutlined", label: <CloudSyncOutlined /> },
	{ value: "CloudTwoTone", label: <CloudTwoTone /> },
	{ value: "CloudUploadOutlined", label: <CloudUploadOutlined /> },
	{ value: "ClusterOutlined", label: <ClusterOutlined /> },
	{ value: "CodeFilled", label: <CodeFilled /> },
	{ value: "CodeOutlined", label: <CodeOutlined /> },
	{ value: "CodeSandboxCircleFilled", label: <CodeSandboxCircleFilled /> },
	{ value: "CodeSandboxOutlined", label: <CodeSandboxOutlined /> },
	{ value: "CodeSandboxSquareFilled", label: <CodeSandboxSquareFilled /> },
	{ value: "CodeTwoTone", label: <CodeTwoTone /> },
	{ value: "CodepenCircleFilled", label: <CodepenCircleFilled /> },
	{ value: "CodepenCircleOutlined", label: <CodepenCircleOutlined /> },
	{ value: "CodepenOutlined", label: <CodepenOutlined /> },
	{ value: "CodepenSquareFilled", label: <CodepenSquareFilled /> },
	{ value: "CoffeeOutlined", label: <CoffeeOutlined /> },
	{ value: "ColumnHeightOutlined", label: <ColumnHeightOutlined /> },
	{ value: "ColumnWidthOutlined", label: <ColumnWidthOutlined /> },
	{ value: "CommentOutlined", label: <CommentOutlined /> },
	{ value: "CompassFilled", label: <CompassFilled /> },
	{ value: "CompassOutlined", label: <CompassOutlined /> },
	{ value: "CompassTwoTone", label: <CompassTwoTone /> },
	{ value: "CompressOutlined", label: <CompressOutlined /> },
	{ value: "ConsoleSqlOutlined", label: <ConsoleSqlOutlined /> },
	{ value: "ContactsFilled", label: <ContactsFilled /> },
	{ value: "ContactsOutlined", label: <ContactsOutlined /> },
	{ value: "ContactsTwoTone", label: <ContactsTwoTone /> },
	{ value: "ContainerFilled", label: <ContainerFilled /> },
	{ value: "ContainerOutlined", label: <ContainerOutlined /> },
	{ value: "ContainerTwoTone", label: <ContainerTwoTone /> },
	{ value: "ControlFilled", label: <ControlFilled /> },
	{ value: "ControlOutlined", label: <ControlOutlined /> },
	{ value: "ControlTwoTone", label: <ControlTwoTone /> },
	{ value: "CopyFilled", label: <CopyFilled /> },
	{ value: "CopyOutlined", label: <CopyOutlined /> },
	{ value: "CopyTwoTone", label: <CopyTwoTone /> },
	{ value: "CopyrightCircleFilled", label: <CopyrightCircleFilled /> },
	{ value: "CopyrightCircleOutlined", label: <CopyrightCircleOutlined /> },
	{ value: "CopyrightCircleTwoTone", label: <CopyrightCircleTwoTone /> },
	{ value: "CopyrightOutlined", label: <CopyrightOutlined /> },
	{ value: "CopyrightTwoTone", label: <CopyrightTwoTone /> },
	{ value: "CreditCardFilled", label: <CreditCardFilled /> },
	{ value: "CreditCardOutlined", label: <CreditCardOutlined /> },
	{ value: "CreditCardTwoTone", label: <CreditCardTwoTone /> },
	{ value: "CrownFilled", label: <CrownFilled /> },
	{ value: "CrownOutlined", label: <CrownOutlined /> },
	{ value: "CrownTwoTone", label: <CrownTwoTone /> },
	{ value: "CustomerServiceFilled", label: <CustomerServiceFilled /> },
	{ value: "CustomerServiceOutlined", label: <CustomerServiceOutlined /> },
	{ value: "CustomerServiceTwoTone", label: <CustomerServiceTwoTone /> },
	{ value: "DashOutlined", label: <DashOutlined /> },
	{ value: "DashboardFilled", label: <DashboardFilled /> },
	{ value: "DashboardOutlined", label: <DashboardOutlined /> },
	{ value: "DashboardTwoTone", label: <DashboardTwoTone /> },
	{ value: "DatabaseFilled", label: <DatabaseFilled /> },
	{ value: "DatabaseOutlined", label: <DatabaseOutlined /> },
	{ value: "DatabaseTwoTone", label: <DatabaseTwoTone /> },
	{ value: "DeleteColumnOutlined", label: <DeleteColumnOutlined /> },
	{ value: "DeleteFilled", label: <DeleteFilled /> },
	{ value: "DeleteOutlined", label: <DeleteOutlined /> },
	{ value: "DeleteRowOutlined", label: <DeleteRowOutlined /> },
	{ value: "DeleteTwoTone", label: <DeleteTwoTone /> },
	{
		value: "DeliveredProcedureOutlined",
		label: <DeliveredProcedureOutlined />,
	},
	{ value: "DeploymentUnitOutlined", label: <DeploymentUnitOutlined /> },
	{ value: "DesktopOutlined", label: <DesktopOutlined /> },
	{ value: "DiffFilled", label: <DiffFilled /> },
	{ value: "DiffOutlined", label: <DiffOutlined /> },
	{ value: "DiffTwoTone", label: <DiffTwoTone /> },
	{ value: "DingdingOutlined", label: <DingdingOutlined /> },
	{ value: "DingtalkCircleFilled", label: <DingtalkCircleFilled /> },
	{ value: "DingtalkOutlined", label: <DingtalkOutlined /> },
	{ value: "DingtalkSquareFilled", label: <DingtalkSquareFilled /> },
	{ value: "DisconnectOutlined", label: <DisconnectOutlined /> },
	{ value: "DislikeFilled", label: <DislikeFilled /> },
	{ value: "DislikeOutlined", label: <DislikeOutlined /> },
	{ value: "DislikeTwoTone", label: <DislikeTwoTone /> },
	{ value: "DollarCircleFilled", label: <DollarCircleFilled /> },
	{ value: "DollarCircleOutlined", label: <DollarCircleOutlined /> },
	{ value: "DollarCircleTwoTone", label: <DollarCircleTwoTone /> },
	{ value: "DollarOutlined", label: <DollarOutlined /> },
	{ value: "DollarTwoTone", label: <DollarTwoTone /> },
	{ value: "DotChartOutlined", label: <DotChartOutlined /> },
	{ value: "DoubleLeftOutlined", label: <DoubleLeftOutlined /> },
	{ value: "DoubleRightOutlined", label: <DoubleRightOutlined /> },
	{ value: "DownCircleFilled", label: <DownCircleFilled /> },
	{ value: "DownCircleOutlined", label: <DownCircleOutlined /> },
	{ value: "DownCircleTwoTone", label: <DownCircleTwoTone /> },
	{ value: "DownOutlined", label: <DownOutlined /> },
	{ value: "DownSquareFilled", label: <DownSquareFilled /> },
	{ value: "DownSquareOutlined", label: <DownSquareOutlined /> },
	{ value: "DownSquareTwoTone", label: <DownSquareTwoTone /> },
	{ value: "DownloadOutlined", label: <DownloadOutlined /> },
	{ value: "DragOutlined", label: <DragOutlined /> },
	{ value: "DribbbleCircleFilled", label: <DribbbleCircleFilled /> },
	{ value: "DribbbleOutlined", label: <DribbbleOutlined /> },
	{ value: "DribbbleSquareFilled", label: <DribbbleSquareFilled /> },
	{ value: "DribbbleSquareOutlined", label: <DribbbleSquareOutlined /> },
	{ value: "DropboxCircleFilled", label: <DropboxCircleFilled /> },
	{ value: "DropboxOutlined", label: <DropboxOutlined /> },
	{ value: "DropboxSquareFilled", label: <DropboxSquareFilled /> },
	{ value: "EditFilled", label: <EditFilled /> },
	{ value: "EditOutlined", label: <EditOutlined /> },
	{ value: "EditTwoTone", label: <EditTwoTone /> },
	{ value: "EllipsisOutlined", label: <EllipsisOutlined /> },
	{ value: "EnterOutlined", label: <EnterOutlined /> },
	{ value: "EnvironmentFilled", label: <EnvironmentFilled /> },
	{ value: "EnvironmentOutlined", label: <EnvironmentOutlined /> },
	{ value: "EnvironmentTwoTone", label: <EnvironmentTwoTone /> },
	{ value: "EuroCircleFilled", label: <EuroCircleFilled /> },
	{ value: "EuroCircleOutlined", label: <EuroCircleOutlined /> },
	{ value: "EuroCircleTwoTone", label: <EuroCircleTwoTone /> },
	{ value: "EuroOutlined", label: <EuroOutlined /> },
	{ value: "EuroTwoTone", label: <EuroTwoTone /> },
	{ value: "ExceptionOutlined", label: <ExceptionOutlined /> },
	{ value: "ExclamationCircleFilled", label: <ExclamationCircleFilled /> },
	{ value: "ExclamationCircleOutlined", label: <ExclamationCircleOutlined /> },
	{ value: "ExclamationCircleTwoTone", label: <ExclamationCircleTwoTone /> },
	{ value: "ExclamationOutlined", label: <ExclamationOutlined /> },
	{ value: "ExpandAltOutlined", label: <ExpandAltOutlined /> },
	{ value: "ExpandOutlined", label: <ExpandOutlined /> },
	{ value: "ExperimentFilled", label: <ExperimentFilled /> },
	{ value: "ExperimentOutlined", label: <ExperimentOutlined /> },
	{ value: "ExperimentTwoTone", label: <ExperimentTwoTone /> },
	{ value: "ExportOutlined", label: <ExportOutlined /> },
	{ value: "EyeFilled", label: <EyeFilled /> },
	{ value: "EyeInvisibleFilled", label: <EyeInvisibleFilled /> },
	{ value: "EyeInvisibleOutlined", label: <EyeInvisibleOutlined /> },
	{ value: "EyeInvisibleTwoTone", label: <EyeInvisibleTwoTone /> },
	{ value: "EyeOutlined", label: <EyeOutlined /> },
	{ value: "EyeTwoTone", label: <EyeTwoTone /> },
	{ value: "FacebookFilled", label: <FacebookFilled /> },
	{ value: "FacebookOutlined", label: <FacebookOutlined /> },
	{ value: "FallOutlined", label: <FallOutlined /> },
	{ value: "FastBackwardFilled", label: <FastBackwardFilled /> },
	{ value: "FastBackwardOutlined", label: <FastBackwardOutlined /> },
	{ value: "FastForwardFilled", label: <FastForwardFilled /> },
	{ value: "FastForwardOutlined", label: <FastForwardOutlined /> },
	{ value: "FieldBinaryOutlined", label: <FieldBinaryOutlined /> },
	{ value: "FieldNumberOutlined", label: <FieldNumberOutlined /> },
	{ value: "FieldStringOutlined", label: <FieldStringOutlined /> },
	{ value: "FieldTimeOutlined", label: <FieldTimeOutlined /> },
	{ value: "FileAddFilled", label: <FileAddFilled /> },
	{ value: "FileAddOutlined", label: <FileAddOutlined /> },
	{ value: "FileAddTwoTone", label: <FileAddTwoTone /> },
	{ value: "FileDoneOutlined", label: <FileDoneOutlined /> },
	{ value: "FileExcelFilled", label: <FileExcelFilled /> },
	{ value: "FileExcelOutlined", label: <FileExcelOutlined /> },
	{ value: "FileExcelTwoTone", label: <FileExcelTwoTone /> },
	{ value: "FileExclamationFilled", label: <FileExclamationFilled /> },
	{ value: "FileExclamationOutlined", label: <FileExclamationOutlined /> },
	{ value: "FileExclamationTwoTone", label: <FileExclamationTwoTone /> },
	{ value: "FileFilled", label: <FileFilled /> },
	{ value: "FileGifOutlined", label: <FileGifOutlined /> },
	{ value: "FileImageFilled", label: <FileImageFilled /> },
	{ value: "FileImageOutlined", label: <FileImageOutlined /> },
	{ value: "FileImageTwoTone", label: <FileImageTwoTone /> },
	{ value: "FileJpgOutlined", label: <FileJpgOutlined /> },
	{ value: "FileMarkdownFilled", label: <FileMarkdownFilled /> },
	{ value: "FileMarkdownOutlined", label: <FileMarkdownOutlined /> },
	{ value: "FileMarkdownTwoTone", label: <FileMarkdownTwoTone /> },
	{ value: "FileOutlined", label: <FileOutlined /> },
	{ value: "FilePdfFilled", label: <FilePdfFilled /> },
	{ value: "FilePdfOutlined", label: <FilePdfOutlined /> },
	{ value: "FilePdfTwoTone", label: <FilePdfTwoTone /> },
	{ value: "FilePptFilled", label: <FilePptFilled /> },
	{ value: "FilePptOutlined", label: <FilePptOutlined /> },
	{ value: "FilePptTwoTone", label: <FilePptTwoTone /> },
	{ value: "FileProtectOutlined", label: <FileProtectOutlined /> },
	{ value: "FileSearchOutlined", label: <FileSearchOutlined /> },
	{ value: "FileSyncOutlined", label: <FileSyncOutlined /> },
	{ value: "FileTextFilled", label: <FileTextFilled /> },
	{ value: "FileTextOutlined", label: <FileTextOutlined /> },
	{ value: "FileTextTwoTone", label: <FileTextTwoTone /> },
	{ value: "FileTwoTone", label: <FileTwoTone /> },
	{ value: "FileUnknownFilled", label: <FileUnknownFilled /> },
	{ value: "FileUnknownOutlined", label: <FileUnknownOutlined /> },
	{ value: "FileUnknownTwoTone", label: <FileUnknownTwoTone /> },
	{ value: "FileWordFilled", label: <FileWordFilled /> },
	{ value: "FileWordOutlined", label: <FileWordOutlined /> },
	{ value: "FileWordTwoTone", label: <FileWordTwoTone /> },
	{ value: "FileZipFilled", label: <FileZipFilled /> },
	{ value: "FileZipOutlined", label: <FileZipOutlined /> },
	{ value: "FileZipTwoTone", label: <FileZipTwoTone /> },
	{ value: "FilterFilled", label: <FilterFilled /> },
	{ value: "FilterOutlined", label: <FilterOutlined /> },
	{ value: "FilterTwoTone", label: <FilterTwoTone /> },
	{ value: "FireFilled", label: <FireFilled /> },
	{ value: "FireOutlined", label: <FireOutlined /> },
	{ value: "FireTwoTone", label: <FireTwoTone /> },
	{ value: "FlagFilled", label: <FlagFilled /> },
	{ value: "FlagOutlined", label: <FlagOutlined /> },
	{ value: "FlagTwoTone", label: <FlagTwoTone /> },
	{ value: "FolderAddFilled", label: <FolderAddFilled /> },
	{ value: "FolderAddOutlined", label: <FolderAddOutlined /> },
	{ value: "FolderAddTwoTone", label: <FolderAddTwoTone /> },
	{ value: "FolderFilled", label: <FolderFilled /> },
	{ value: "FolderOpenFilled", label: <FolderOpenFilled /> },
	{ value: "FolderOpenOutlined", label: <FolderOpenOutlined /> },
	{ value: "FolderOpenTwoTone", label: <FolderOpenTwoTone /> },
	{ value: "FolderOutlined", label: <FolderOutlined /> },
	{ value: "FolderTwoTone", label: <FolderTwoTone /> },
	{ value: "FolderViewOutlined", label: <FolderViewOutlined /> },
	{ value: "FontColorsOutlined", label: <FontColorsOutlined /> },
	{ value: "FontSizeOutlined", label: <FontSizeOutlined /> },
	{ value: "ForkOutlined", label: <ForkOutlined /> },
	{ value: "FormOutlined", label: <FormOutlined /> },
	{ value: "FormatPainterFilled", label: <FormatPainterFilled /> },
	{ value: "FormatPainterOutlined", label: <FormatPainterOutlined /> },
	{ value: "ForwardFilled", label: <ForwardFilled /> },
	{ value: "ForwardOutlined", label: <ForwardOutlined /> },
	{ value: "FrownFilled", label: <FrownFilled /> },
	{ value: "FrownOutlined", label: <FrownOutlined /> },
	{ value: "FrownTwoTone", label: <FrownTwoTone /> },
	{ value: "FullscreenExitOutlined", label: <FullscreenExitOutlined /> },
	{ value: "FullscreenOutlined", label: <FullscreenOutlined /> },
	{ value: "FunctionOutlined", label: <FunctionOutlined /> },
	{ value: "FundFilled", label: <FundFilled /> },
	{ value: "FundOutlined", label: <FundOutlined /> },
	{
		value: "FundProjectionScreenOutlined",
		label: <FundProjectionScreenOutlined />,
	},
	{ value: "FundTwoTone", label: <FundTwoTone /> },
	{ value: "FundViewOutlined", label: <FundViewOutlined /> },
	{ value: "FunnelPlotFilled", label: <FunnelPlotFilled /> },
	{ value: "FunnelPlotOutlined", label: <FunnelPlotOutlined /> },
	{ value: "FunnelPlotTwoTone", label: <FunnelPlotTwoTone /> },
	{ value: "GatewayOutlined", label: <GatewayOutlined /> },
	{ value: "GifOutlined", label: <GifOutlined /> },
	{ value: "GiftFilled", label: <GiftFilled /> },
	{ value: "GiftOutlined", label: <GiftOutlined /> },
	{ value: "GiftTwoTone", label: <GiftTwoTone /> },
	{ value: "GithubFilled", label: <GithubFilled /> },
	{ value: "GithubOutlined", label: <GithubOutlined /> },
	{ value: "GitlabFilled", label: <GitlabFilled /> },
	{ value: "GitlabOutlined", label: <GitlabOutlined /> },
	{ value: "GlobalOutlined", label: <GlobalOutlined /> },
	{ value: "GoldFilled", label: <GoldFilled /> },
	{ value: "GoldOutlined", label: <GoldOutlined /> },
	{ value: "GoldTwoTone", label: <GoldTwoTone /> },
	{ value: "GoldenFilled", label: <GoldenFilled /> },
	{ value: "GoogleCircleFilled", label: <GoogleCircleFilled /> },
	{ value: "GoogleOutlined", label: <GoogleOutlined /> },
	{ value: "GooglePlusCircleFilled", label: <GooglePlusCircleFilled /> },
	{ value: "GooglePlusOutlined", label: <GooglePlusOutlined /> },
	{ value: "GooglePlusSquareFilled", label: <GooglePlusSquareFilled /> },
	{ value: "GoogleSquareFilled", label: <GoogleSquareFilled /> },
	{ value: "GroupOutlined", label: <GroupOutlined /> },
	{ value: "HddFilled", label: <HddFilled /> },
	{ value: "HddOutlined", label: <HddOutlined /> },
	{ value: "HddTwoTone", label: <HddTwoTone /> },
	{ value: "HeartFilled", label: <HeartFilled /> },
	{ value: "HeartOutlined", label: <HeartOutlined /> },
	{ value: "HeartTwoTone", label: <HeartTwoTone /> },
	{ value: "HeatMapOutlined", label: <HeatMapOutlined /> },
	{ value: "HighlightFilled", label: <HighlightFilled /> },
	{ value: "HighlightOutlined", label: <HighlightOutlined /> },
	{ value: "HighlightTwoTone", label: <HighlightTwoTone /> },
	{ value: "HistoryOutlined", label: <HistoryOutlined /> },
	{ value: "HolderOutlined", label: <HolderOutlined /> },
	{ value: "HomeFilled", label: <HomeFilled /> },
	{ value: "HomeOutlined", label: <HomeOutlined /> },
	{ value: "HomeTwoTone", label: <HomeTwoTone /> },
	{ value: "HourglassFilled", label: <HourglassFilled /> },
	{ value: "HourglassOutlined", label: <HourglassOutlined /> },
	{ value: "HourglassTwoTone", label: <HourglassTwoTone /> },
	{ value: "Html5Filled", label: <Html5Filled /> },
	{ value: "Html5Outlined", label: <Html5Outlined /> },
	{ value: "Html5TwoTone", label: <Html5TwoTone /> },
	{ value: "IdcardFilled", label: <IdcardFilled /> },
	{ value: "IdcardOutlined", label: <IdcardOutlined /> },
	{ value: "IdcardTwoTone", label: <IdcardTwoTone /> },
	{ value: "IeCircleFilled", label: <IeCircleFilled /> },
	{ value: "IeOutlined", label: <IeOutlined /> },
	{ value: "IeSquareFilled", label: <IeSquareFilled /> },
	{ value: "ImportOutlined", label: <ImportOutlined /> },
	{ value: "InboxOutlined", label: <InboxOutlined /> },
	{ value: "InfoCircleFilled", label: <InfoCircleFilled /> },
	{ value: "InfoCircleOutlined", label: <InfoCircleOutlined /> },
	{ value: "InfoCircleTwoTone", label: <InfoCircleTwoTone /> },
	{ value: "InfoOutlined", label: <InfoOutlined /> },
	{ value: "InsertRowAboveOutlined", label: <InsertRowAboveOutlined /> },
	{ value: "InsertRowBelowOutlined", label: <InsertRowBelowOutlined /> },
	{ value: "InsertRowLeftOutlined", label: <InsertRowLeftOutlined /> },
	{ value: "InsertRowRightOutlined", label: <InsertRowRightOutlined /> },
	{ value: "InstagramFilled", label: <InstagramFilled /> },
	{ value: "InstagramOutlined", label: <InstagramOutlined /> },
	{ value: "InsuranceFilled", label: <InsuranceFilled /> },
	{ value: "InsuranceOutlined", label: <InsuranceOutlined /> },
	{ value: "InsuranceTwoTone", label: <InsuranceTwoTone /> },
	{ value: "InteractionFilled", label: <InteractionFilled /> },
	{ value: "InteractionOutlined", label: <InteractionOutlined /> },
	{ value: "InteractionTwoTone", label: <InteractionTwoTone /> },
	{ value: "IssuesCloseOutlined", label: <IssuesCloseOutlined /> },
	{ value: "ItalicOutlined", label: <ItalicOutlined /> },
	{ value: "KeyOutlined", label: <KeyOutlined /> },
	{ value: "LaptopOutlined", label: <LaptopOutlined /> },
	{ value: "LayoutFilled", label: <LayoutFilled /> },
	{ value: "LayoutOutlined", label: <LayoutOutlined /> },
	{ value: "LayoutTwoTone", label: <LayoutTwoTone /> },
	{ value: "LeftCircleFilled", label: <LeftCircleFilled /> },
	{ value: "LeftCircleOutlined", label: <LeftCircleOutlined /> },
	{ value: "LeftCircleTwoTone", label: <LeftCircleTwoTone /> },
	{ value: "LeftOutlined", label: <LeftOutlined /> },
	{ value: "LeftSquareFilled", label: <LeftSquareFilled /> },
	{ value: "LeftSquareOutlined", label: <LeftSquareOutlined /> },
	{ value: "LeftSquareTwoTone", label: <LeftSquareTwoTone /> },
	{ value: "LikeFilled", label: <LikeFilled /> },
	{ value: "LikeOutlined", label: <LikeOutlined /> },
	{ value: "LikeTwoTone", label: <LikeTwoTone /> },
	{ value: "LineChartOutlined", label: <LineChartOutlined /> },
	{ value: "LineHeightOutlined", label: <LineHeightOutlined /> },
	{ value: "LineOutlined", label: <LineOutlined /> },
	{ value: "LinkOutlined", label: <LinkOutlined /> },
	{ value: "LinkedinFilled", label: <LinkedinFilled /> },
	{ value: "LinkedinOutlined", label: <LinkedinOutlined /> },
	{ value: "Loading3QuartersOutlined", label: <Loading3QuartersOutlined /> },
	{ value: "LoadingOutlined", label: <LoadingOutlined /> },
	{ value: "LockFilled", label: <LockFilled /> },
	{ value: "LockOutlined", label: <LockOutlined /> },
	{ value: "LockTwoTone", label: <LockTwoTone /> },
	{ value: "LoginOutlined", label: <LoginOutlined /> },
	{ value: "LogoutOutlined", label: <LogoutOutlined /> },
	{ value: "MacCommandFilled", label: <MacCommandFilled /> },
	{ value: "MacCommandOutlined", label: <MacCommandOutlined /> },
	{ value: "MailFilled", label: <MailFilled /> },
	{ value: "MailOutlined", label: <MailOutlined /> },
	{ value: "MailTwoTone", label: <MailTwoTone /> },
	{ value: "ManOutlined", label: <ManOutlined /> },
	{ value: "MedicineBoxFilled", label: <MedicineBoxFilled /> },
	{ value: "MedicineBoxOutlined", label: <MedicineBoxOutlined /> },
	{ value: "MedicineBoxTwoTone", label: <MedicineBoxTwoTone /> },
	{ value: "MediumCircleFilled", label: <MediumCircleFilled /> },
	{ value: "MediumOutlined", label: <MediumOutlined /> },
	{ value: "MediumSquareFilled", label: <MediumSquareFilled /> },
	{ value: "MediumWorkmarkOutlined", label: <MediumWorkmarkOutlined /> },
	{ value: "MehFilled", label: <MehFilled /> },
	{ value: "MehOutlined", label: <MehOutlined /> },
	{ value: "MehTwoTone", label: <MehTwoTone /> },
	{ value: "MenuFoldOutlined", label: <MenuFoldOutlined /> },
	{ value: "MenuOutlined", label: <MenuOutlined /> },
	{ value: "MenuUnfoldOutlined", label: <MenuUnfoldOutlined /> },
	{ value: "MergeCellsOutlined", label: <MergeCellsOutlined /> },
	{ value: "MessageFilled", label: <MessageFilled /> },
	{ value: "MessageOutlined", label: <MessageOutlined /> },
	{ value: "MessageTwoTone", label: <MessageTwoTone /> },
	{ value: "MinusCircleFilled", label: <MinusCircleFilled /> },
	{ value: "MinusCircleOutlined", label: <MinusCircleOutlined /> },
	{ value: "MinusCircleTwoTone", label: <MinusCircleTwoTone /> },
	{ value: "MinusOutlined", label: <MinusOutlined /> },
	{ value: "MinusSquareFilled", label: <MinusSquareFilled /> },
	{ value: "MinusSquareOutlined", label: <MinusSquareOutlined /> },
	{ value: "MinusSquareTwoTone", label: <MinusSquareTwoTone /> },
	{ value: "MobileFilled", label: <MobileFilled /> },
	{ value: "MobileOutlined", label: <MobileOutlined /> },
	{ value: "MobileTwoTone", label: <MobileTwoTone /> },
	{ value: "MoneyCollectFilled", label: <MoneyCollectFilled /> },
	{ value: "MoneyCollectOutlined", label: <MoneyCollectOutlined /> },
	{ value: "MoneyCollectTwoTone", label: <MoneyCollectTwoTone /> },
	{ value: "MonitorOutlined", label: <MonitorOutlined /> },
	{ value: "MoreOutlined", label: <MoreOutlined /> },
	{ value: "NodeCollapseOutlined", label: <NodeCollapseOutlined /> },
	{ value: "NodeExpandOutlined", label: <NodeExpandOutlined /> },
	{ value: "NodeIndexOutlined", label: <NodeIndexOutlined /> },
	{ value: "NotificationFilled", label: <NotificationFilled /> },
	{ value: "NotificationOutlined", label: <NotificationOutlined /> },
	{ value: "NotificationTwoTone", label: <NotificationTwoTone /> },
	{ value: "NumberOutlined", label: <NumberOutlined /> },
	{ value: "OneToOneOutlined", label: <OneToOneOutlined /> },
	{ value: "OrderedListOutlined", label: <OrderedListOutlined /> },
	{ value: "PaperClipOutlined", label: <PaperClipOutlined /> },
	{ value: "PartitionOutlined", label: <PartitionOutlined /> },
	{ value: "PauseCircleFilled", label: <PauseCircleFilled /> },
	{ value: "PauseCircleOutlined", label: <PauseCircleOutlined /> },
	{ value: "PauseCircleTwoTone", label: <PauseCircleTwoTone /> },
	{ value: "PauseOutlined", label: <PauseOutlined /> },
	{ value: "PayCircleFilled", label: <PayCircleFilled /> },
	{ value: "PayCircleOutlined", label: <PayCircleOutlined /> },
	{ value: "PercentageOutlined", label: <PercentageOutlined /> },
	{ value: "PhoneFilled", label: <PhoneFilled /> },
	{ value: "PhoneOutlined", label: <PhoneOutlined /> },
	{ value: "PhoneTwoTone", label: <PhoneTwoTone /> },
	{ value: "PicCenterOutlined", label: <PicCenterOutlined /> },
	{ value: "PicLeftOutlined", label: <PicLeftOutlined /> },
	{ value: "PicRightOutlined", label: <PicRightOutlined /> },
	{ value: "PictureFilled", label: <PictureFilled /> },
	{ value: "PictureOutlined", label: <PictureOutlined /> },
	{ value: "PictureTwoTone", label: <PictureTwoTone /> },
	{ value: "PieChartFilled", label: <PieChartFilled /> },
	{ value: "PieChartOutlined", label: <PieChartOutlined /> },
	{ value: "PieChartTwoTone", label: <PieChartTwoTone /> },
	{ value: "PlayCircleFilled", label: <PlayCircleFilled /> },
	{ value: "PlayCircleOutlined", label: <PlayCircleOutlined /> },
	{ value: "PlayCircleTwoTone", label: <PlayCircleTwoTone /> },
	{ value: "PlaySquareFilled", label: <PlaySquareFilled /> },
	{ value: "PlaySquareOutlined", label: <PlaySquareOutlined /> },
	{ value: "PlaySquareTwoTone", label: <PlaySquareTwoTone /> },
	{ value: "PlusCircleFilled", label: <PlusCircleFilled /> },
	{ value: "PlusCircleOutlined", label: <PlusCircleOutlined /> },
	{ value: "PlusCircleTwoTone", label: <PlusCircleTwoTone /> },
	{ value: "PlusOutlined", label: <PlusOutlined /> },
	{ value: "PlusSquareFilled", label: <PlusSquareFilled /> },
	{ value: "PlusSquareOutlined", label: <PlusSquareOutlined /> },
	{ value: "PlusSquareTwoTone", label: <PlusSquareTwoTone /> },
	{ value: "PoundCircleFilled", label: <PoundCircleFilled /> },
	{ value: "PoundCircleOutlined", label: <PoundCircleOutlined /> },
	{ value: "PoundCircleTwoTone", label: <PoundCircleTwoTone /> },
	{ value: "PoundOutlined", label: <PoundOutlined /> },
	{ value: "PoweroffOutlined", label: <PoweroffOutlined /> },
	{ value: "PrinterFilled", label: <PrinterFilled /> },
	{ value: "PrinterOutlined", label: <PrinterOutlined /> },
	{ value: "PrinterTwoTone", label: <PrinterTwoTone /> },
	{ value: "ProfileFilled", label: <ProfileFilled /> },
	{ value: "ProfileOutlined", label: <ProfileOutlined /> },
	{ value: "ProfileTwoTone", label: <ProfileTwoTone /> },
	{ value: "ProjectFilled", label: <ProjectFilled /> },
	{ value: "ProjectOutlined", label: <ProjectOutlined /> },
	{ value: "ProjectTwoTone", label: <ProjectTwoTone /> },
	{ value: "PropertySafetyFilled", label: <PropertySafetyFilled /> },
	{ value: "PropertySafetyOutlined", label: <PropertySafetyOutlined /> },
	{ value: "PropertySafetyTwoTone", label: <PropertySafetyTwoTone /> },
	{ value: "PullRequestOutlined", label: <PullRequestOutlined /> },
	{ value: "PushpinFilled", label: <PushpinFilled /> },
	{ value: "PushpinOutlined", label: <PushpinOutlined /> },
	{ value: "PushpinTwoTone", label: <PushpinTwoTone /> },
	{ value: "QqCircleFilled", label: <QqCircleFilled /> },
	{ value: "QqOutlined", label: <QqOutlined /> },
	{ value: "QqSquareFilled", label: <QqSquareFilled /> },
	{ value: "QrcodeOutlined", label: <QrcodeOutlined /> },
	{ value: "QuestionCircleFilled", label: <QuestionCircleFilled /> },
	{ value: "QuestionCircleOutlined", label: <QuestionCircleOutlined /> },
	{ value: "QuestionCircleTwoTone", label: <QuestionCircleTwoTone /> },
	{ value: "QuestionOutlined", label: <QuestionOutlined /> },
	{ value: "RadarChartOutlined", label: <RadarChartOutlined /> },
	{ value: "RadiusBottomleftOutlined", label: <RadiusBottomleftOutlined /> },
	{ value: "RadiusBottomrightOutlined", label: <RadiusBottomrightOutlined /> },
	{ value: "RadiusSettingOutlined", label: <RadiusSettingOutlined /> },
	{ value: "RadiusUpleftOutlined", label: <RadiusUpleftOutlined /> },
	{ value: "RadiusUprightOutlined", label: <RadiusUprightOutlined /> },
	{ value: "ReadFilled", label: <ReadFilled /> },
	{ value: "ReadOutlined", label: <ReadOutlined /> },
	{ value: "ReconciliationFilled", label: <ReconciliationFilled /> },
	{ value: "ReconciliationOutlined", label: <ReconciliationOutlined /> },
	{ value: "ReconciliationTwoTone", label: <ReconciliationTwoTone /> },
	{ value: "RedEnvelopeFilled", label: <RedEnvelopeFilled /> },
	{ value: "RedEnvelopeOutlined", label: <RedEnvelopeOutlined /> },
	{ value: "RedEnvelopeTwoTone", label: <RedEnvelopeTwoTone /> },
	{ value: "RedditCircleFilled", label: <RedditCircleFilled /> },
	{ value: "RedditOutlined", label: <RedditOutlined /> },
	{ value: "RedditSquareFilled", label: <RedditSquareFilled /> },
	{ value: "RedoOutlined", label: <RedoOutlined /> },
	{ value: "ReloadOutlined", label: <ReloadOutlined /> },
	{ value: "RestFilled", label: <RestFilled /> },
	{ value: "RestOutlined", label: <RestOutlined /> },
	{ value: "RestTwoTone", label: <RestTwoTone /> },
	{ value: "RetweetOutlined", label: <RetweetOutlined /> },
	{ value: "RightCircleFilled", label: <RightCircleFilled /> },
	{ value: "RightCircleOutlined", label: <RightCircleOutlined /> },
	{ value: "RightCircleTwoTone", label: <RightCircleTwoTone /> },
	{ value: "RightOutlined", label: <RightOutlined /> },
	{ value: "RightSquareFilled", label: <RightSquareFilled /> },
	{ value: "RightSquareOutlined", label: <RightSquareOutlined /> },
	{ value: "RightSquareTwoTone", label: <RightSquareTwoTone /> },
	{ value: "RiseOutlined", label: <RiseOutlined /> },
	{ value: "RobotFilled", label: <RobotFilled /> },
	{ value: "RobotOutlined", label: <RobotOutlined /> },
	{ value: "RocketFilled", label: <RocketFilled /> },
	{ value: "RocketOutlined", label: <RocketOutlined /> },
	{ value: "RocketTwoTone", label: <RocketTwoTone /> },
	{ value: "RollbackOutlined", label: <RollbackOutlined /> },
	{ value: "RotateLeftOutlined", label: <RotateLeftOutlined /> },
	{ value: "RotateRightOutlined", label: <RotateRightOutlined /> },
	{ value: "SafetyCertificateFilled", label: <SafetyCertificateFilled /> },
	{ value: "SafetyCertificateOutlined", label: <SafetyCertificateOutlined /> },
	{ value: "SafetyCertificateTwoTone", label: <SafetyCertificateTwoTone /> },
	{ value: "SafetyOutlined", label: <SafetyOutlined /> },
	{ value: "SaveFilled", label: <SaveFilled /> },
	{ value: "SaveOutlined", label: <SaveOutlined /> },
	{ value: "SaveTwoTone", label: <SaveTwoTone /> },
	{ value: "ScanOutlined", label: <ScanOutlined /> },
	{ value: "ScheduleFilled", label: <ScheduleFilled /> },
	{ value: "ScheduleOutlined", label: <ScheduleOutlined /> },
	{ value: "ScheduleTwoTone", label: <ScheduleTwoTone /> },
	{ value: "ScissorOutlined", label: <ScissorOutlined /> },
	{ value: "SearchOutlined", label: <SearchOutlined /> },
	{ value: "SecurityScanFilled", label: <SecurityScanFilled /> },
	{ value: "SecurityScanOutlined", label: <SecurityScanOutlined /> },
	{ value: "SecurityScanTwoTone", label: <SecurityScanTwoTone /> },
	{ value: "SelectOutlined", label: <SelectOutlined /> },
	{ value: "SendOutlined", label: <SendOutlined /> },
	{ value: "SettingFilled", label: <SettingFilled /> },
	{ value: "SettingOutlined", label: <SettingOutlined /> },
	{ value: "SettingTwoTone", label: <SettingTwoTone /> },
	{ value: "ShakeOutlined", label: <ShakeOutlined /> },
	{ value: "ShareAltOutlined", label: <ShareAltOutlined /> },
	{ value: "ShopFilled", label: <ShopFilled /> },
	{ value: "ShopOutlined", label: <ShopOutlined /> },
	{ value: "ShopTwoTone", label: <ShopTwoTone /> },
	{ value: "ShoppingCartOutlined", label: <ShoppingCartOutlined /> },
	{ value: "ShoppingFilled", label: <ShoppingFilled /> },
	{ value: "ShoppingOutlined", label: <ShoppingOutlined /> },
	{ value: "ShoppingTwoTone", label: <ShoppingTwoTone /> },
	{ value: "ShrinkOutlined", label: <ShrinkOutlined /> },
	{ value: "SignalFilled", label: <SignalFilled /> },
	{ value: "SisternodeOutlined", label: <SisternodeOutlined /> },
	{ value: "SketchCircleFilled", label: <SketchCircleFilled /> },
	{ value: "SketchOutlined", label: <SketchOutlined /> },
	{ value: "SketchSquareFilled", label: <SketchSquareFilled /> },
	{ value: "SkinFilled", label: <SkinFilled /> },
	{ value: "SkinOutlined", label: <SkinOutlined /> },
	{ value: "SkinTwoTone", label: <SkinTwoTone /> },
	{ value: "SkypeFilled", label: <SkypeFilled /> },
	{ value: "SkypeOutlined", label: <SkypeOutlined /> },
	{ value: "SlackCircleFilled", label: <SlackCircleFilled /> },
	{ value: "SlackOutlined", label: <SlackOutlined /> },
	{ value: "SlackSquareFilled", label: <SlackSquareFilled /> },
	{ value: "SlackSquareOutlined", label: <SlackSquareOutlined /> },
	{ value: "SlidersFilled", label: <SlidersFilled /> },
	{ value: "SlidersOutlined", label: <SlidersOutlined /> },
	{ value: "SlidersTwoTone", label: <SlidersTwoTone /> },
	{ value: "SmallDashOutlined", label: <SmallDashOutlined /> },
	{ value: "SmileFilled", label: <SmileFilled /> },
	{ value: "SmileOutlined", label: <SmileOutlined /> },
	{ value: "SmileTwoTone", label: <SmileTwoTone /> },
	{ value: "SnippetsFilled", label: <SnippetsFilled /> },
	{ value: "SnippetsOutlined", label: <SnippetsOutlined /> },
	{ value: "SnippetsTwoTone", label: <SnippetsTwoTone /> },
	{ value: "SolutionOutlined", label: <SolutionOutlined /> },
	{ value: "SortAscendingOutlined", label: <SortAscendingOutlined /> },
	{ value: "SortDescendingOutlined", label: <SortDescendingOutlined /> },
	{ value: "SoundFilled", label: <SoundFilled /> },
	{ value: "SoundOutlined", label: <SoundOutlined /> },
	{ value: "SoundTwoTone", label: <SoundTwoTone /> },
	{ value: "SplitCellsOutlined", label: <SplitCellsOutlined /> },
	{ value: "StarFilled", label: <StarFilled /> },
	{ value: "StarOutlined", label: <StarOutlined /> },
	{ value: "StarTwoTone", label: <StarTwoTone /> },
	{ value: "StepBackwardFilled", label: <StepBackwardFilled /> },
	{ value: "StepBackwardOutlined", label: <StepBackwardOutlined /> },
	{ value: "StepForwardFilled", label: <StepForwardFilled /> },
	{ value: "StepForwardOutlined", label: <StepForwardOutlined /> },
	{ value: "StockOutlined", label: <StockOutlined /> },
	{ value: "StopFilled", label: <StopFilled /> },
	{ value: "StopOutlined", label: <StopOutlined /> },
	{ value: "StopTwoTone", label: <StopTwoTone /> },
	{ value: "StrikethroughOutlined", label: <StrikethroughOutlined /> },
	{ value: "SubnodeOutlined", label: <SubnodeOutlined /> },
	{ value: "SwapLeftOutlined", label: <SwapLeftOutlined /> },
	{ value: "SwapOutlined", label: <SwapOutlined /> },
	{ value: "SwapRightOutlined", label: <SwapRightOutlined /> },
	{ value: "SwitcherFilled", label: <SwitcherFilled /> },
	{ value: "SwitcherOutlined", label: <SwitcherOutlined /> },
	{ value: "SwitcherTwoTone", label: <SwitcherTwoTone /> },
	{ value: "SyncOutlined", label: <SyncOutlined /> },
	{ value: "TableOutlined", label: <TableOutlined /> },
	{ value: "TabletFilled", label: <TabletFilled /> },
	{ value: "TabletOutlined", label: <TabletOutlined /> },
	{ value: "TabletTwoTone", label: <TabletTwoTone /> },
	{ value: "TagFilled", label: <TagFilled /> },
	{ value: "TagOutlined", label: <TagOutlined /> },
	{ value: "TagTwoTone", label: <TagTwoTone /> },
	{ value: "TagsFilled", label: <TagsFilled /> },
	{ value: "TagsOutlined", label: <TagsOutlined /> },
	{ value: "TagsTwoTone", label: <TagsTwoTone /> },
	{ value: "TaobaoCircleFilled", label: <TaobaoCircleFilled /> },
	{ value: "TaobaoCircleOutlined", label: <TaobaoCircleOutlined /> },
	{ value: "TaobaoOutlined", label: <TaobaoOutlined /> },
	{ value: "TaobaoSquareFilled", label: <TaobaoSquareFilled /> },
	{ value: "TeamOutlined", label: <TeamOutlined /> },
	{ value: "ThunderboltFilled", label: <ThunderboltFilled /> },
	{ value: "ThunderboltOutlined", label: <ThunderboltOutlined /> },
	{ value: "ThunderboltTwoTone", label: <ThunderboltTwoTone /> },
	{ value: "ToTopOutlined", label: <ToTopOutlined /> },
	{ value: "ToolFilled", label: <ToolFilled /> },
	{ value: "ToolOutlined", label: <ToolOutlined /> },
	{ value: "ToolTwoTone", label: <ToolTwoTone /> },
	{ value: "TrademarkCircleFilled", label: <TrademarkCircleFilled /> },
	{ value: "TrademarkCircleOutlined", label: <TrademarkCircleOutlined /> },
	{ value: "TrademarkCircleTwoTone", label: <TrademarkCircleTwoTone /> },
	{ value: "TrademarkOutlined", label: <TrademarkOutlined /> },
	{ value: "TransactionOutlined", label: <TransactionOutlined /> },
	{ value: "TranslationOutlined", label: <TranslationOutlined /> },
	{ value: "TrophyFilled", label: <TrophyFilled /> },
	{ value: "TrophyOutlined", label: <TrophyOutlined /> },
	{ value: "TrophyTwoTone", label: <TrophyTwoTone /> },
	{ value: "TwitterCircleFilled", label: <TwitterCircleFilled /> },
	{ value: "TwitterOutlined", label: <TwitterOutlined /> },
	{ value: "TwitterSquareFilled", label: <TwitterSquareFilled /> },
	{ value: "UnderlineOutlined", label: <UnderlineOutlined /> },
	{ value: "UndoOutlined", label: <UndoOutlined /> },
	{ value: "UngroupOutlined", label: <UngroupOutlined /> },
	{ value: "UnlockFilled", label: <UnlockFilled /> },
	{ value: "UnlockOutlined", label: <UnlockOutlined /> },
	{ value: "UnlockTwoTone", label: <UnlockTwoTone /> },
	{ value: "UnorderedListOutlined", label: <UnorderedListOutlined /> },
	{ value: "UpCircleFilled", label: <UpCircleFilled /> },
	{ value: "UpCircleOutlined", label: <UpCircleOutlined /> },
	{ value: "UpCircleTwoTone", label: <UpCircleTwoTone /> },
	{ value: "UpOutlined", label: <UpOutlined /> },
	{ value: "UpSquareFilled", label: <UpSquareFilled /> },
	{ value: "UpSquareOutlined", label: <UpSquareOutlined /> },
	{ value: "UpSquareTwoTone", label: <UpSquareTwoTone /> },
	{ value: "UploadOutlined", label: <UploadOutlined /> },
	{ value: "UsbFilled", label: <UsbFilled /> },
	{ value: "UsbOutlined", label: <UsbOutlined /> },
	{ value: "UsbTwoTone", label: <UsbTwoTone /> },
	{ value: "UserAddOutlined", label: <UserAddOutlined /> },
	{ value: "UserDeleteOutlined", label: <UserDeleteOutlined /> },
	{ value: "UserOutlined", label: <UserOutlined /> },
	{ value: "UserSwitchOutlined", label: <UserSwitchOutlined /> },
	{ value: "UsergroupAddOutlined", label: <UsergroupAddOutlined /> },
	{ value: "UsergroupDeleteOutlined", label: <UsergroupDeleteOutlined /> },
	{ value: "VerifiedOutlined", label: <VerifiedOutlined /> },
	{
		value: "VerticalAlignBottomOutlined",
		label: <VerticalAlignBottomOutlined />,
	},
	{
		value: "VerticalAlignMiddleOutlined",
		label: <VerticalAlignMiddleOutlined />,
	},
	{ value: "VerticalAlignTopOutlined", label: <VerticalAlignTopOutlined /> },
	{ value: "VerticalLeftOutlined", label: <VerticalLeftOutlined /> },
	{ value: "VerticalRightOutlined", label: <VerticalRightOutlined /> },
	{ value: "VideoCameraAddOutlined", label: <VideoCameraAddOutlined /> },
	{ value: "VideoCameraFilled", label: <VideoCameraFilled /> },
	{ value: "VideoCameraOutlined", label: <VideoCameraOutlined /> },
	{ value: "VideoCameraTwoTone", label: <VideoCameraTwoTone /> },
	{ value: "WalletFilled", label: <WalletFilled /> },
	{ value: "WalletOutlined", label: <WalletOutlined /> },
	{ value: "WalletTwoTone", label: <WalletTwoTone /> },
	{ value: "WarningFilled", label: <WarningFilled /> },
	{ value: "WarningOutlined", label: <WarningOutlined /> },
	{ value: "WarningTwoTone", label: <WarningTwoTone /> },
	{ value: "WechatFilled", label: <WechatFilled /> },
	{ value: "WechatOutlined", label: <WechatOutlined /> },
	{ value: "WeiboCircleFilled", label: <WeiboCircleFilled /> },
	{ value: "WeiboCircleOutlined", label: <WeiboCircleOutlined /> },
	{ value: "WeiboOutlined", label: <WeiboOutlined /> },
	{ value: "WeiboSquareFilled", label: <WeiboSquareFilled /> },
	{ value: "WeiboSquareOutlined", label: <WeiboSquareOutlined /> },
	{ value: "WhatsAppOutlined", label: <WhatsAppOutlined /> },
	{ value: "WifiOutlined", label: <WifiOutlined /> },
	{ value: "WindowsFilled", label: <WindowsFilled /> },
	{ value: "WindowsOutlined", label: <WindowsOutlined /> },
	{ value: "WomanOutlined", label: <WomanOutlined /> },
	{ value: "YahooFilled", label: <YahooFilled /> },
	{ value: "YahooOutlined", label: <YahooOutlined /> },
	{ value: "YoutubeFilled", label: <YoutubeFilled /> },
	{ value: "YoutubeOutlined", label: <YoutubeOutlined /> },
	{ value: "YuqueFilled", label: <YuqueFilled /> },
	{ value: "YuqueOutlined", label: <YuqueOutlined /> },
	{ value: "ZhihuCircleFilled", label: <ZhihuCircleFilled /> },
	{ value: "ZhihuOutlined", label: <ZhihuOutlined /> },
	{ value: "ZhihuSquareFilled", label: <ZhihuSquareFilled /> },
	{ value: "ZoomInOutlined", label: <ZoomInOutlined /> },
	{ value: "ZoomOutOutlined", label: <ZoomOutOutlined /> },
];
